### PR TITLE
Jest

### PR DESCRIPTION
**Pull request by latrujil913**
Added base jest testing library and example unit tests

### CODE REVIEW

**Review by GabrielMarquez0852 — APPROVED** [review]
Looks good

**Comment by BrandonSYu** [comment]
Looks great. I think testing branch should be separate from a deployment branch.

**Review by BrandonSYu — COMMENTED** [review]
Looks good. I think testing should be a separate branch from deployment.

**Review by Zoolyn — APPROVED** [review]
looks good to me

**Pull request merged**
