### PR TITLE
Counting

### PR DESCRIPTION
**Pull request by GabrielMarquez0852**
- Added Calm Counting feature

- Includes conditional rendering and handling of data from a selection screen.

### CODE REVIEW

**Review by jackzhen1996 — APPROVED** [review]
looks good

**Review by jackzhen1996 — APPROVED** [review]
Looks good!

**Review by latrujil913 — CHANGES_REQUESTED** [review]
Can you remove the jest files

**Review by latrujil913 — APPROVED** [review]
Looks good

**Pull request merged**
